import React from 'react'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
	title: 'My Page Title',
	description: 'Generated by My_App',
}

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<title>{metadata.title}</title>
				<meta name="description" content={metadata.description} />

				<body>
					<main>{children}</main>
				</body>
			</html>
		</ClerkProvider>
	)
}
