import Header from '@/components/_layouts/Header'
import './globals.css'
import Footer from '@/components/_layouts/Footer'

export const metadata = {
	title: 'My_App',
	description: 'Generated by My_App',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	)
}
