import './globals.css'

export const metadata = {
	title: 'My_App',
	description: 'Generated by My_App',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
