import React from 'react'
import RecoilContextProvider from '@/app/lib/recoil/recoilContextProvider'
import HeaderSettings from '@/components/_layouts/HedearSettings'
import FooterArchives from '@/components/_layouts/FooterArchives'

export const metadata = {
	title: 'My_App',
	description: 'Generated by My_App',
}

export default function RootLayout({ children }) {
	return (
		<RecoilContextProvider>
			<HeaderSettings />
			<div>{children}</div>
			<FooterArchives />
		</RecoilContextProvider>
	)
}
